#############################
# Chrony Monitoring (numeric)
# Compatible with Zabbix Agent / Agent2
# -------------------------------------
# ---- Global Sources Status  ----
UserParameter=chrony_global_sources_status_all,chrony_global_sources_status all
UserParameter=chrony_global_sources_status_current,chrony_global_sources_status current
# ---- Global Status  ----
# Global Chrony Service Status (text)
UserParameter=chrony_global_status,chrony_global_status
UserParameter=chrony_global_status_numeric,chrony_global_status --numeric
# ---- Tracking Metrics ----
# Stratum level (integer)
#UserParameter=chrony.stratum,chronyc -n tracking | awk '/Stratum/ {print $3}'
UserParameter=chrony.stratum,chronyc -n sources | grep '^\^\*' | awk '{print $3}'
# Last offset (seconds, float)
UserParameter=chrony.offset,chronyc -n tracking | awk '/Last offset/ {print $4}'
# RMS offset (seconds, float)
UserParameter=chrony.rms_offset,chronyc -n tracking | awk '/RMS offset/ {print $4}'
# Frequency (ppm, float)
UserParameter=chrony.freq,chronyc -n tracking | awk '/Frequency/ {print $3}'
# Residual frequency (ppm, float)
UserParameter=chrony.res_freq,chronyc -n tracking | awk '/Residual freq/ {print $3}'
# Skew (ppm, float)
UserParameter=chrony.skew,chronyc -n tracking | awk '/Skew/ {print $3}'
# Root delay (seconds, float)
UserParameter=chrony.root_delay,chronyc -n tracking | awk '/Root delay/ {print $4}'
# Root dispersion (seconds, float)
UserParameter=chrony.root_dispersion,chronyc -n tracking | awk '/Root dispersion/ {print $4}'
# Update interval (seconds, float)
UserParameter=chrony.update_interval,chronyc -n tracking | awk '/Update interval/ {print $3}'
# Leap status (numeric: Normal=0, Not sync=1, etc.)
UserParameter=chrony.leap_status,chronyc -n tracking | awk '/Leap status/ {if($3=="Normal")print 0; else print 1}'
# ---- Sources Metrics ----
# Count of reachable sources (integer)
UserParameter=chrony.sources_reach,chronyc -n sources | awk '/^[\^\*]/ {c++} END {print c+0}'
# Active source offset (microseconds)
UserParameter=chrony.active_offset,chronyc -n sources | awk '/^\^?\*/ {sub(/[\[\]]/,""); print $3}' | tr -d 'us'
# Number of total sources (integer)
UserParameter=chrony.sources_total,chronyc -n sources | awk '/^[\^\+\-\*]/ {c++} END {print c+0}'
